// This file is generated by rust-protobuf 2.22.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `KeyAndNonce.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_22_0;

#[derive(PartialEq,Clone,Default)]
pub struct KeyAndNonce {
    // message fields
    pub data_key: ::std::vec::Vec<u8>,
    pub data_nonce: ::std::vec::Vec<u8>,
    pub nonce_for_key: ::std::vec::Vec<u8>,
    pub nonce_for_nonce: ::std::vec::Vec<u8>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a KeyAndNonce {
    fn default() -> &'a KeyAndNonce {
        <KeyAndNonce as ::protobuf::Message>::default_instance()
    }
}

impl KeyAndNonce {
    pub fn new() -> KeyAndNonce {
        ::std::default::Default::default()
    }

    // bytes data_key = 1;


    pub fn get_data_key(&self) -> &[u8] {
        &self.data_key
    }
    pub fn clear_data_key(&mut self) {
        self.data_key.clear();
    }

    // Param is passed by value, moved
    pub fn set_data_key(&mut self, v: ::std::vec::Vec<u8>) {
        self.data_key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data_key(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data_key
    }

    // Take field
    pub fn take_data_key(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data_key, ::std::vec::Vec::new())
    }

    // bytes data_nonce = 2;


    pub fn get_data_nonce(&self) -> &[u8] {
        &self.data_nonce
    }
    pub fn clear_data_nonce(&mut self) {
        self.data_nonce.clear();
    }

    // Param is passed by value, moved
    pub fn set_data_nonce(&mut self, v: ::std::vec::Vec<u8>) {
        self.data_nonce = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_data_nonce(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.data_nonce
    }

    // Take field
    pub fn take_data_nonce(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.data_nonce, ::std::vec::Vec::new())
    }

    // bytes nonce_for_key = 3;


    pub fn get_nonce_for_key(&self) -> &[u8] {
        &self.nonce_for_key
    }
    pub fn clear_nonce_for_key(&mut self) {
        self.nonce_for_key.clear();
    }

    // Param is passed by value, moved
    pub fn set_nonce_for_key(&mut self, v: ::std::vec::Vec<u8>) {
        self.nonce_for_key = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nonce_for_key(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.nonce_for_key
    }

    // Take field
    pub fn take_nonce_for_key(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.nonce_for_key, ::std::vec::Vec::new())
    }

    // bytes nonce_for_nonce = 4;


    pub fn get_nonce_for_nonce(&self) -> &[u8] {
        &self.nonce_for_nonce
    }
    pub fn clear_nonce_for_nonce(&mut self) {
        self.nonce_for_nonce.clear();
    }

    // Param is passed by value, moved
    pub fn set_nonce_for_nonce(&mut self, v: ::std::vec::Vec<u8>) {
        self.nonce_for_nonce = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_nonce_for_nonce(&mut self) -> &mut ::std::vec::Vec<u8> {
        &mut self.nonce_for_nonce
    }

    // Take field
    pub fn take_nonce_for_nonce(&mut self) -> ::std::vec::Vec<u8> {
        ::std::mem::replace(&mut self.nonce_for_nonce, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for KeyAndNonce {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data_key)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.data_nonce)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.nonce_for_key)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_bytes_into(wire_type, is, &mut self.nonce_for_nonce)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.data_key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.data_key);
        }
        if !self.data_nonce.is_empty() {
            my_size += ::protobuf::rt::bytes_size(2, &self.data_nonce);
        }
        if !self.nonce_for_key.is_empty() {
            my_size += ::protobuf::rt::bytes_size(3, &self.nonce_for_key);
        }
        if !self.nonce_for_nonce.is_empty() {
            my_size += ::protobuf::rt::bytes_size(4, &self.nonce_for_nonce);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.data_key.is_empty() {
            os.write_bytes(1, &self.data_key)?;
        }
        if !self.data_nonce.is_empty() {
            os.write_bytes(2, &self.data_nonce)?;
        }
        if !self.nonce_for_key.is_empty() {
            os.write_bytes(3, &self.nonce_for_key)?;
        }
        if !self.nonce_for_nonce.is_empty() {
            os.write_bytes(4, &self.nonce_for_nonce)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> KeyAndNonce {
        KeyAndNonce::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "data_key",
                |m: &KeyAndNonce| { &m.data_key },
                |m: &mut KeyAndNonce| { &mut m.data_key },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "data_nonce",
                |m: &KeyAndNonce| { &m.data_nonce },
                |m: &mut KeyAndNonce| { &mut m.data_nonce },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "nonce_for_key",
                |m: &KeyAndNonce| { &m.nonce_for_key },
                |m: &mut KeyAndNonce| { &mut m.nonce_for_key },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "nonce_for_nonce",
                |m: &KeyAndNonce| { &m.nonce_for_nonce },
                |m: &mut KeyAndNonce| { &mut m.nonce_for_nonce },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<KeyAndNonce>(
                "KeyAndNonce",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static KeyAndNonce {
        static instance: ::protobuf::rt::LazyV2<KeyAndNonce> = ::protobuf::rt::LazyV2::INIT;
        instance.get(KeyAndNonce::new)
    }
}

impl ::protobuf::Clear for KeyAndNonce {
    fn clear(&mut self) {
        self.data_key.clear();
        self.data_nonce.clear();
        self.nonce_for_key.clear();
        self.nonce_for_nonce.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for KeyAndNonce {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KeyAndNonce {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x11KeyAndNonce.proto\"\x93\x01\n\x0bKeyAndNonce\x12\x19\n\x08data_key\
    \x18\x01\x20\x01(\x0cR\x07dataKey\x12\x1d\n\ndata_nonce\x18\x02\x20\x01(\
    \x0cR\tdataNonce\x12\"\n\rnonce_for_key\x18\x03\x20\x01(\x0cR\x0bnonceFo\
    rKey\x12&\n\x0fnonce_for_nonce\x18\x04\x20\x01(\x0cR\rnonceForNonceJ\x86\
    \x02\n\x06\x12\x04\0\0\x07\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\n\n\n\x02\
    \x04\0\x12\x04\x02\0\x07\x01\n\n\n\x03\x04\0\x01\x12\x03\x02\x08\x13\n\
    \x0b\n\x04\x04\0\x02\0\x12\x03\x03\x04\x17\n\x0c\n\x05\x04\0\x02\0\x05\
    \x12\x03\x03\x04\t\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x03\n\x12\n\x0c\n\
    \x05\x04\0\x02\0\x03\x12\x03\x03\x15\x16\n\x0b\n\x04\x04\0\x02\x01\x12\
    \x03\x04\x04\x19\n\x0c\n\x05\x04\0\x02\x01\x05\x12\x03\x04\x04\t\n\x0c\n\
    \x05\x04\0\x02\x01\x01\x12\x03\x04\n\x14\n\x0c\n\x05\x04\0\x02\x01\x03\
    \x12\x03\x04\x17\x18\n\x0b\n\x04\x04\0\x02\x02\x12\x03\x05\x04\x1c\n\x0c\
    \n\x05\x04\0\x02\x02\x05\x12\x03\x05\x04\t\n\x0c\n\x05\x04\0\x02\x02\x01\
    \x12\x03\x05\n\x17\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x05\x1a\x1b\n\
    \x0b\n\x04\x04\0\x02\x03\x12\x03\x06\x04\x1e\n\x0c\n\x05\x04\0\x02\x03\
    \x05\x12\x03\x06\x04\t\n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x06\n\x19\n\
    \x0c\n\x05\x04\0\x02\x03\x03\x12\x03\x06\x1c\x1db\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
